services:
  db:
    image: postgres:18 # Specifying 18 explicitly keeps it predictable
    container_name: postgres_database
    restart: always
    environment:
      POSTGRES_USER: test_user 
      POSTGRES_PASSWORD: secretkey 
      POSTGRES_DB: test_db 
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql # FIXED: Changed path to match Postgres 18 structures
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d test_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: application
    restart: always
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload 
    ports: 
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://test_user:secretkey@db:5432/test_db
      - SECRETKEY=mYseCretKey
    volumes:
      - .:/code 
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:

